config/routes.rb
Rails.application.routes.draw do
  resources :pumps
  get 'welcome/index'
  root 'welcome#index'

  resources :jobs do
    resources :parts do
      put 'finish'
    end

    put :sort, on: :collection

    member do
      put 'finish'
      put 'activate'
    end

    resources :pumps do
    end
  end

  match '/reports' => 'reports#index', via: [:get]
  match '/reports/active_jobs' => 'reports#active_jobs', via: [:get]
  match '/reports/finished_jobs' => 'reports#finished_jobs', via: [:get]
  match '/reports/job_summary/:jobNum' => 'reports#job_summary', via: [:get], as: :job_report
  match '/reports/:jobNum' => 'reports#show', via: [:get], as: :individual_report
  match '/reports/bill_of_materials/:jobNum' => 'reports#bill_of_materials', via: [:get], as: :job_bom
end

app/models/part.rb
class Part < ApplicationRecord
  before_create :update_part_item_num
  after_destroy :update_part_item_num
  validates :partNum, :item_num, uniqueness: true
  belongs_to :job

  private
  def update_part_item_num
    if self.new_record?
      self.item_num = self.class.where('job_id = ?', self.job_id).count.to_i+1
    else
      nil
    end

    if self.destroyed?
      self.class.where('item_num > ?', self.item_num_was).update_all('item_num = item_num - 1')
    else
      nil
    end
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :load_job,:set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.preload(:job)
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
    @job = Job.find(params[:job_id])
    @part = @job.parts.find(params[:id])

    respond_to do |format|
      format.html
      format.json {render json: @part}
    end
  end

  # GET /parts/new
  def new
    @job = Job.find(params[:job_id])
    @part = @job.parts.build

    respond_to do |format|
      format.html
      format.json {render json: @part}
    end
  end

  # GET /parts/1/edit
  def edit
    @job = Job.find(params[:job_id])
    @part = @job.parts.find(params[:id])
  end

  # POST /parts
  # POST /parts.json
  def create
    @job = Job.find(params[:job_id])
    @part = @job.parts.build(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to edit_job_path(@job), notice: 'Part was successfully created.' }
        format.json { render json: @job, action:edit, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    @job = Job.find(params[:job_id])
    @part = @job.parts.find(params[:id])

    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to edit_job_path(@job.id), notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render edit_job_part_path(@job) }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @job = Job.find(params[:job_id])
    @part = @job.parts.find(params[:id])
    @part.destroy
    respond_to do |format|
      format.html { redirect_to edit_job_path(@job), notice: 'Part was successfully destroyed.' }
      format.json { head :ok }
    end
  end

  def finish
    @job = Job.find(params[:job_id])
    @part = @job.parts.find(params[:id])
    @part.update_attribute(:finished, true)

    respond_to do |format|
      format.js {render inline: 'location.reload();'}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def load_job
      @job = Job.find(params[:job_id])
    end

    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:partNum, :description, :quantity, :totalQuantity, :workOrder, :finish, :job_id, :item_num)
    end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_form.html.erb
<%= form_with model: [@job, @part], id: :part_form, local: true do |form| %>
  <% if @part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
      <% part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.label 'Part Number:' %>
    <%= form.text_field :partNum, id: :part_partNum %>

    <%= form.label 'Description:' %>
    <%= form.text_area :description, id: :part_description %>

    <%= form.label 'Quantity Per Pump:' %>
    <%= form.number_field :quantity, id: :part_quantity %>

    <%= form.label 'Total Quantity:' %>
    <%= form.number_field :totalQuantity, id: :part_totalQuantity %>

    <%= form.label 'Work Order Required?' %>
    <%= form.text_field :workOrder, id: :part_workOrder %>

    <% content_for :local_menu do %>
        <%= link_to  job_path(@job) do %>
            <li class="local-nav-tab">Finish Part</li>
        <% end %>
        <%= link_to job_part_path(@job, part), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <li class="local-nav-tab">Cancel Part</li>
        <% end %>
        <%= link_to '', onclick:"$('#part_form').submit()" do %>
            <li class="local-nav-tab">Update Part</li>
        <% end %>
    <% end %>
<% end %>

app/views/parts/_index.html.erb
<div class="tableHeader">
  <div class="dataColumn">Item Number</div>
  <div class="dataColumn">Part Number</div>
  <div class="dataColumn hidden">Customer</div>
  <div class="textColumn">Description</div>
  <div class="dataColumn hidden">Need BOM</div>
  <div class="dataColumn hidden">BOM Done</div>
  <div class="dataColumn">Quantity</div>
  <div class="dataColumn">Total Quantity</div>
  <div class="dataColumn">Work Order</div>
  <div class="dataColumn hidden">Priority</div>
  <div class="dataColumn">Finished?</div>
  <div class="dataColumn hidden">Edit</div>
  <div class="dataColumn hidden">Cancel</div>

</div>

<% job.parts.each do |part| %>
    <div class="<%= part.item_num.odd? ? 'odd-part' : 'even-part' %> row">
      <div class="data"><%= part.item_num %></div>
      <div class="data"><%= part.partNum %></div>
      <div class="data hidden">Customer</div>
      <div class="textData"><%= part.description %></div>
      <div class="data hidden">Need BOM</div>
      <div class="data hidden">BOM Done</div>
      <div class="data"><%= part.quantity %></div>
      <div class="data"><%= part.totalQuantity %></div>
      <div class="data"><%= part.workOrder %></div>
      <div class="data hidden">progress</div>
      <% if part.finished? %>
          <div class="data">Yes</div>
      <% else %>
          <div class="data"><%= link_to 'Finish',jobs_path, class:'finish-btn', method: 'put', remote: true %></div>
      <% end %>
      <div class="data"><%= link_to 'Edit', edit_job_part_path(job, part), class: 'edit-btn' %></div>
      <div class="data"><%= link_to 'Cancel', job_part_path(job, part), method: :delete, data: {confirm: 'Are you sure?'}, class: 'delete-btn' %></div>
    </div>
<% end %>

app/views/parts/edit.html.erb
<h1>Editing Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Back', edit_job_path(@part.job_id) %>

app/views/parts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parts</h1>

<table>
  <thead>
    <tr>
      <th>Partnum</th>
      <th>Description</th>
      <th>Quanitity</th>
      <th>Totalquantity</th>
      <th>Workorder</th>
      <th>Finish</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parts.each do |part| %>
      <tr>
        <td><%= part.partNum %></td>
        <td><%= part.description %></td>
        <td><%= part.quanitity %></td>
        <td><%= part.totalQuantity %></td>
        <td><%= part.workOrder %></td>
        <td><%= part.finish %></td>
        <td><%= link_to 'Show', part %></td>
        <td><%= link_to 'Edit', edit_job_part_path(part) %></td>
        <td><%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Part', new_job_part_path %>

app/views/parts/new.html.erb
<h1>New Part for Job <%= @job.jobNum %></h1>

<%= render 'form', part: new_job_part_path(@job) %>

<%= link_to 'Back', edit_job_path(@job) %>

app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Partnum:</strong>
  <%= @part.partNum %>
</p>

<p>
  <strong>Description:</strong>
  <%= @part.description %>
</p>

<p>
  <strong>Quanitity:</strong>
  <%= @part.quanitity %>
</p>

<p>
  <strong>Totalquantity:</strong>
  <%= @part.totalQuantity %>
</p>

<p>
  <strong>Workorder:</strong>
  <%= @part.workOrder %>
</p>

<p>
  <strong>Finish:</strong>
  <%= @part.finish %>
</p>

<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>