config/routes.rb
Rails.application.routes.draw do
  resources :pumps
  get 'welcome/index'
  root 'welcome#index'

  resources :jobs do
    resources :parts do
      put 'finish'
    end

    put :sort, on: :collection

    member do
      put 'finish'
      put 'activate'
    end

    resources :pumps do
    end
  end

  match '/reports' => 'reports#index', via: [:get]
  match '/reports/active_jobs' => 'reports#active_jobs', via: [:get]
  match '/reports/finished_jobs' => 'reports#finished_jobs', via: [:get]
  match '/reports/job_summary/:jobNum' => 'reports#job_summary', via: [:get], as: :job_report
  match '/reports/:jobNum' => 'reports#show', via: [:get], as: :individual_report
  match '/reports/bill_of_materials/:jobNum' => 'reports#bill_of_materials', via: [:get], as: :job_bom
end

app/models/job.rb
class Job < ApplicationRecord
  before_save :update_priorities
  validates :priority, :jobNum, uniqueness: true
  has_many :parts, -> { order(item_num: :asc)}, dependent: :destroy
  has_many :pumps, dependent: :destroy
  default_scope{ order('priority ASC')}

  private
  def update_priorities
    if self.priority_was == nil
      self.class.where('priority >= ?', self.priority).update_all('priority = priority + 1')
    else
      nil
    end

    if self.priority_changed? and self.priority_was != nil
      if self.priority < self.priority_was
        self.class.where('priority >= ?', self.priority).update_all('priority = priority + 1')
        self.class.where('priority > ?', self.priority_was).update_all('priority = priority - 1')
      else
        nil
      end

      if self.priority > self.priority_was
        self.class.where('priority <= ?', self.priority).update_all('priority = priority - 1')
        self.class.where('priority < ?', self.priority_was).update_all('priority = priority + 1')
      else
        nil
      end
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :load_parts, :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    if params[:finished] == nil or params[:finished] == 'false'
      @jobs = Job.where('finished = ?', false).preload(:parts, :pumps)
    else
      @jobs = Job.where('finished = ?', true).preload(:parts, :pumps)
    end

    respond_to do |format|
      format.html {render 'index'}
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save&&@job.work_type.exclude?('Pump')
        format.html { redirect_to jobs_path, notice: 'Job was successfully created.' }
        format.json { render @job, status: :created, location: @job }
      elsif @job.save&&@job.work_type.include?('Pump')
        format.html { redirect_to new_job_pump_path(@job.id), notice: 'Job was successfully created.' }
        format.json { render @job, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to jobs_path, notice: 'Job was successfully updated.' }
        format.json { render :index, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sort
    @jobs = Job.all.preload(:parts, :pumps)
    old_priority = params[:oldPriority].to_i+1
    new_priority = params[:newPriority].to_i+1
    @job = Job.find_by_priority(old_priority)
    @job.update_attribute(:priority, new_priority)

    respond_to do |format|
      format.js {render inline: 'location.reload();'}
    end
  end

  def finish
    @jobs = Job.order(:priority)
    @job = Job.find(params[:id])
    @job.update_attribute(:finished, true)
    @job.update_attribute(:priority, @jobs.last.priority)
    @job.parts.update_all(finished: true)

    respond_to do |format|
      format.js {render inline: 'location.reload();'}
    end
  end

  def activate
    @jobs = Job.order(:priority)
    @job = Job.find(params[:id])
    @job.update_attribute(:finished, false)
    @job.update_attribute(:priority, @job.priority_was)
    @job.parts.update_all(finished: false)

    respond_to do |format|
      format.js {render inline: 'location.reload();'}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    def load_parts
      @parts = Part.where('job_id = ?', params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:jobNum, :poDate, :customer, :description, :needBom, :bomDone, :status, :progress, :priority, :finished, :dueDate, :work_type)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, id: :job_form, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= form.label 'Job Number' %>
    <%= form.number_field :jobNum, id: :job_jobNum %>


    <%= form.label 'Purchase Date' %>
    <%= form.date_field :poDate, id: :job_poDate, data:{provide:'datepicker'} %>

    <%= form.label 'Due Date' %>
    <%= form.date_field :dueDate, id: :job_dueDate, data:{provide: 'datepicker'} %>

    <%= form.label 'Type of Job' %>
    <%= form.select :work_type, options_for_select(['Horizontal Pump', 'Vertical Pump', 'Motor', 'Repair', 'Replacement Parts'], selected: form.object.work_type), include_blank: true, id: :job_type %>

    <%= form.label 'Customer' %>
    <%= form.text_field :customer, id: :job_customer %>

    <%= form.label 'Description' %>
    <%= form.text_area :description, id: :job_description %>

    <%= form.label 'Need BOM?' %>
    <%= form.check_box :needBom, id: :job_needBom %>

    <%= form.label 'Is the BOM done?' %>
    <%= form.check_box :bomDone, id: :job_bomDone %>

    <%= form.label 'What is the current Status?' %>
    <%= form.select :status, options_for_select([['Engineering'],['Production'],['Finished'],['Shipped']], selected: form.object.status), include_blank: true %>

    <%= form.label 'What is the current Progress?' %>
    <%= form.text_area :progress, id: :job_progress %>

    <%= form.label 'Priority' %>
    <%= form.number_field :priority, id: :job_priority %>
<% end %>

app/views/jobs/_index.html.erb
<% @jobs.each do |job| %>
    <div class="job-block">
      <div id="job_<%= job.id %>" class="<%= job.priority.odd? ? 'odd' : 'even' %> row"  data-update-url="<%= job.id %>">
        <div class="data"><%= job.jobNum %></div>
        <div class="data"><%= job.work_type %></div>
        <div class="data"><%= job.dueDate.try(:strftime, '%b %d, %Y') %></div>
        <div class="data"><%= job.customer %></div>
        <div class="data"><%= job.description %></div>
        <% if job.needBom? %>
            <div class="data">Yes</div>
        <% else %>
            <div class="data">No</div>
        <% end %>
        <% if job.bomDone? %>
            <div class="data">Yes</div>
        <% else %>
            <div class="data">No</div>
        <% end %>
        <div class="data"><%= job.status %></div>
        <div class="data"><%= job.progress %></div>

        <% if job.finished? %>
            <div class="data">N/A</div>
        <% else %>
            <div class="data"><%= job.priority %></div>
        <% end %>

        <% if job.finished? %>
            <div class="data"><%= link_to 'Activate', activate_job_path(job, @job), class:'finish-btn', method: 'put', remote: true %></div>
        <% else %>
            <div class="data"><%= link_to 'Finish', finish_job_path(job, @job), class:'finish-btn', method: 'put', remote: true %></div>
        <% end %>

        <div class="data"><%= link_to 'Edit', edit_job_path(job), class: 'edit-btn' %></div>
        <div class="data"><%= link_to 'Cancel', job, method: :delete, data: { confirm: 'Are you sure?' }, class:'delete-btn' %></div>
      </div>

      <% if job.pumps.exists? %>
        <div class="parts-block list-header">
          <div class="data"><h3>Pumps:</h3></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
        </div>

        <div class="parts-block parts-header">
          <div class="dataColumn">Item Number</div>
          <div class="dataColumn">Pump Type</div>
          <div class="dataColumn">Quantity</div>
          <div class="dataColumn">Stages</div>
          <div class="dataColumn hidden">Need BOM</div>
          <div class="dataColumn hidden">BOM Done?</div>
          <div class="dataColumn">Flow Rate</div>
          <div class="dataColumn">Total Developed Head (TDH)</div>
          <div class="dataColumn">Provided Assemblies</div>
          <div class="dataColumn">Restrictions</div>
          <div class="dataColumn">Finished?</div>
          <div class="dataColumn hidden">Edit</div>
          <div class="dataColumn hidden">Cancel</div>
        </div>
        <% job.pumps.each do |pump| %>
          <div class="parts-block <%= pump.item_num.odd? ? 'odd-part' : 'even-part' %>">
            <div class="data"><%= pump.item_num %></div>
            <div class="data"><%= pump.product_type %></div>
            <div class="data"><%= pump.quantity %></div>
            <div class="data"><%= pump.stages %></div>
            <div class="data hidden">Need BOM</div>
            <div class="data hidden">BOM Done?</div>
            <div class="data"><%= pump.flowrate %></div>
            <div class="data"><%= pump.dev_head %></div>
            <div class="data"><%= pump.assembly %></div>
            <div class="data"><%= pump.restrictions %></div>
            <div class="data hidden">Finished</div>
            <div class="data"><%= link_to 'Edit', edit_job_pump_path(job, pump), class: 'edit-btn' %></div>
            <div class="data hidden">Cancel</div>
          </div>
        <% end %>

      <% else %>
      <% end %>

      <% if job.parts.exists? %>
        <div class="parts-block list-header">
          <div class="data"><h3>Parts:</h3></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
        </div>

        <div class="parts-block parts-header">
          <div class="dataColumn">Item Number</div>
          <div class="dataColumn">Part Number</div>
          <div class="dataColumn hidden">Customer</div>
          <div class="dataColumn">Description</div>
          <div class="dataColumn hidden">Need BOM</div>
          <div class="dataColumn hidden">BOM Done?</div>
          <div class="dataColumn">Quantity/Pump</div>
          <div class="dataColumn">Total Quantity</div>
          <div class="dataColumn">Work Order?</div>
          <div class="dataColumn hidden">Priority</div>
          <div class="dataColumn">Finished?</div>
          <div class="dataColumn hidden">Edit</div>
          <div class="dataColumn hidden">Cancel</div>
        </div>
        <% job.parts.each do |part| %>
            <div class="parts-block <%= part.item_num.odd? ? 'odd-part' : 'even-part' %>">
              <div class="data"><%= part.item_num %></div>
              <div class="data"><%= part.partNum %></div>
              <div class="data hidden">Customer</div>
              <div class="data"><%= part.description %></div>
              <div class="data hidden">Need BOM</div>
              <div class="data hidden">BOM Done?</div>
              <div class="data"><%= part.quantity %></div>
              <div class="data"><%= part.totalQuantity %></div>
              <div class="data"><%= part.workOrder %></div>
              <div class="data hidden">Priority</div>
              <% if part.finished? %>
                  <div class="data">Yes</div>
              <% else %>
                  <div class="data"><%= link_to 'Finish', jobs_path, class:'finish-btn' %></div>
              <% end %>
              <div class="data"><%= link_to 'Edit', edit_job_part_path(job, part), class: 'edit-btn' %></div>
              <div class="data hidden">Cancel</div>
            </div>
        <% end %>
      <% else %>
        <div class="parts-block message-line">
          <div class="data"><h3>No Items</h3></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
          <div class="data"></div>
        </div>
      <% end %>
    </div>


<% end %>

app/views/jobs/edit.html.erb
<% content_for :local_menu do %>
    <%= link_to  jobs_path do %>
        <li class="local-nav-tab">Finish Job</li>
    <% end %>
    <%= link_to @job, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <li class="local-nav-tab">Cancel Job</li>
    <% end %>
    <%= link_to '', onclick:"$('#job_form').submit()" do %>
        <li class="local-nav-tab">Save Job</li>
    <% end %>
    <%= link_to  new_job_part_path(@job) do %>
        <li class="local-nav-tab">New Part</li>
    <% end %>
    <%= link_to jobs_path, finished: false do %>
        <li class="local-nav-tab">Return to Jobs</li>
    <% end %>
<% end %>

<h1>Editing Job</h1>

<div class="form-grid">
  <%= render 'form', job: @job %>
</div>
<br />
<br />
<br />

<% if @job.pumps.exists? %>
  <h2>Pumps:</h2>
  <div class="table">
    <div class="tableRows">
      <%= render partial: 'pumps/index', locals: {job: @job} %>
    </div>
  </div>
<% else %>
<% end %>

<% if @job.parts.exists? %>

  <h2>Parts:</h2>
  <div class="table">
    <div class="tableRows">
      <%= render partial: 'parts/index', locals: {job: @job} %>
    </div>
  </div>
<% else %>
<% end %>

app/views/jobs/index.html.erb
<% content_for :local_menu do %>
    <%= link_to  jobs_path do %>
        <li class="local-nav-tab">Universal Parts</li>
    <% end %>
    <%= link_to jobs_path(finished: true) do %>
        <li class="local-nav-tab">Finished Jobs</li>
    <% end %>
    <%= link_to  reports_path do %>
        <li class="local-nav-tab">New Job Report</li>
    <% end %>
    <%= link_to  new_job_path do %>
        <li class="local-nav-tab">New Job</li>
    <% end %>
<% end %>

<p id="notice"><%= notice %></p>

  <div class="table">
    <div id="sticky-anchor">
      <div id="sticky" class="tableHeader">
        <div class="dataColumn">Job Number</div>
        <div class="dataColumn">Type of Work</div>
        <div class="dataColumn">Due Date</div>
        <div class="dataColumn">Customer</div>
        <div class="dataColumn">Description</div>
        <div class="dataColumn">Need BOM</div>
        <div class="dataColumn">BOM done?</div>
        <div class="dataColumn">Status</div>
        <div class="dataColumn">Progress</div>
        <div class="dataColumn">Priority</div>
        <div class="dataColumn hidden btn-header">Finished</div>
        <div class="dataColumn hidden btn-header">Edit</div>
        <div class="dataColumn hidden btn-header">Cancel</div>
      </div>
    </div>

    <div class="tableHeader">
      <div class="dataColumn">Job Number</div>
      <div class="dataColumn">Type of Work</div>
      <div class="dataColumn">Due Date</div>
      <div class="dataColumn">Customer</div>
      <div class="dataColumn">Description</div>
      <div class="dataColumn">Need BOM</div>
      <div class="dataColumn">BOM done?</div>
      <div class="dataColumn">Status</div>
      <div class="dataColumn">Progress</div>
      <div class="dataColumn">Priority</div>
      <div class="dataColumn hidden">Finished</div>
      <div class="dataColumn hidden btn-header">Edit</div>
      <div class="dataColumn hidden btn-header">Cancel</div>
    </div>

    <div id="sortable" class="tableRows">
      <%= render 'index', locals: {jobs: @jobs} %>
    </div>
  </div>
  <br />

app/views/jobs/new.html.erb
<% content_for :local_menu do %>
    <%= link_to '', onclick:"$('#job_form').submit()" do %>
        <li class="local-nav-tab">Save Job</li>
    <% end %>
    <%= link_to jobs_path(finished: true) do %>
        <li class="local-nav-tab">Return to Jobs</li>
    <% end %>
<% end %>


<h1>New Job</h1>

<%= render 'form', job: @job %>

app/views/jobs/reports.html.erb
<h1>Please select a report:</h1>

<%= link_to  reports_active_jobs_path(format: 'pdf') do %>
    <div class="list-buttons">Active Jobs Report</div>
<% end %>
<br />
<%= link_to  reports_finished_jobs_path(format: 'pdf') do %>
    <div class="list-buttons">Finished Jobs Report</div>
<% end %>
<br />

<div id="job-sum-block" class="job-report-block">
  <div id="job_sum" class="job-input list-buttons">
    Individual Job Summary
  </div>
  <div class="job-input-form odd">
    <%= select_tag 'Job Report', options_from_collection_for_select(@jobs, 'jobNum', 'jobNum'), include_blank: true %>
    <%= link_to 'Generate Report', job_report_path(jobNum: ' ', format: 'pdf'), class: 'finish-btn report', id: 'report-link' %>
  </div>
</div>
<br />

<div id="job-bom-block" class="job-report-block">
  <div id="job_bom" class="job-input list-buttons">
    Bill of Materials for Specific Job
  </div>
  <div class="job-input-form odd">
    <%= select_tag 'Job BOM', options_from_collection_for_select(@jobs, 'jobNum', 'jobNum') %>
    <%= link_to 'BOM Report', job_bom_path(jobNum: ' ', format: 'pdf'), class:'finish-btn report', id: 'bom-link' %>
  </div>
</div>
<br />

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Jobnum:</strong>
  <%= @job.jobNum %>
</p>

<p>
  <strong>Podate:</strong>
  <%= @job.poDate %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @job.customer %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Needbom:</strong>
  <%= @job.needBom %>
</p>

<p>
  <strong>Bomdone:</strong>
  <%= @job.bomDone %>
</p>

<p>
  <strong>Status:</strong>
  <%= @job.status %>
</p>

<p>
  <strong>Progress:</strong>
  <%= @job.progress %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @job.priority %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/sort.js.erb
$('#sortable').html("<%= escape_javascript render partial: 'index', locals: {jobs: @jobs} %>")