config/routes.rb
Rails.application.routes.draw do
  resources :pumps
  get 'welcome/index'
  root 'welcome#index'

  resources :jobs do
    resources :parts do
      put 'finish'
    end

    put :sort, on: :collection

    member do
      put 'finish'
      put 'activate'
    end

    resources :pumps do
    end
  end

  match '/reports' => 'reports#index', via: [:get]
  match '/reports/active_jobs' => 'reports#active_jobs', via: [:get]
  match '/reports/finished_jobs' => 'reports#finished_jobs', via: [:get]
  match '/reports/job_summary/:jobNum' => 'reports#job_summary', via: [:get], as: :job_report
  match '/reports/:jobNum' => 'reports#show', via: [:get], as: :individual_report
  match '/reports/bill_of_materials/:jobNum' => 'reports#bill_of_materials', via: [:get], as: :job_bom
end

app/models/pump.rb
class Pump < ApplicationRecord
  before_create :update_pump_item_num
  before_destroy :update_pump_item_num
  belongs_to :job

  private
  def update_pump_item_num
    if self.new_record?
      self.item_num = self.class.where('job_id = ?', self.job_id).count.to_i+1
    else
      nil
    end

    if self.destroyed?
      self.class.where('item_num > ?', self.item_num_was).update_all('item_num = item_num - 1')
    else
      nil
    end
  end
end

app/controllers/pumps_controller.rb
class PumpsController < ApplicationController
  before_action :set_job, :set_pump, only: [:show, :edit, :update, :destroy]

  # GET /pumps
  # GET /pumps.json
  def index
    @pumps = Pump.preload(:job)
  end

  # GET /pumps/1
  # GET /pumps/1.json
  def show
    @job = Job.find(params[:job_id])
    @pump = @job.pumps.find(params[:id])
  end

  # GET /pumps/new
  def new
    @job = Job.find(params[:job_id])
    @pump = @job.pumps.build
  end

  # GET /pumps/1/edit
  def edit
    @job = Job.find(params[:job_id])
    @pump = @job.pumps.find(params[:id])
  end

  # POST /pumps
  # POST /pumps.json
  def create
    @job = Job.find(params[:job_id])
    @pump = @job.pumps.build(pump_params)

    respond_to do |format|
      if @pump.save
        format.html { redirect_to job_pump_path(@job.id, @pump.id), notice: 'Pump was successfully created.' }
        format.json { render :show, status: :created, location: @pump }
      else
        format.html { render :new }
        format.json { render json: @pump.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pumps/1
  # PATCH/PUT /pumps/1.json
  def update
    @job = Job.find(params[:job_id])
    @pump = @job.pumps.find(params[:id])

    respond_to do |format|
      if @pump.update(pump_params)
        format.html { redirect_to job_pump_path(@job.id, @pump.id), notice: 'Pump was successfully updated.' }
        format.json { render :show, status: :ok, location: @pump }
      else
        format.html { render :edit }
        format.json { render json: @pump.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pumps/1
  # DELETE /pumps/1.json
  def destroy
    @pump = Pump.find_by job_id: @job.id, id: params[:id]

    @pump.destroy

    respond_to do |format|
      format.html { redirect_to edit_job_path(@job), notice: 'Pump was successfully destroyed.' }
      format.json { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @pump = Pump.find(params[:id])
      @job = Job.find(@pump.job_id)
    end
    def set_pump
      @pump = Pump.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pump_params
      params.require(:pump).permit(:product_type, :stages, :flowrate, :dev_head, :assembly, :restrictions, :quantity, :job_id, :item_num)
    end
end

app/helpers/pumps_helper.rb
module PumpsHelper
end

app/views/pumps/_form.html.erb
<%= form_with(model: [@job, @pump], local: true) do |form| %>
  <% if @pump.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pump.errors.count, "error") %> prohibited this pump from being saved:</h2>

      <ul>
      <% pump.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Product Type' %>
    <%= form.text_field :product_type, id: :pump_product_type %>
  </div>

  <div class="field">
    <%= form.label 'Item Number' %>
    <%= form.text_field :item_num, id: :pump_item_num %>
  </div>

  <div class="field">
    <%= form.label 'Stages' %>
    <%= form.number_field :stages, id: :pump_stages %>
  </div>

  <div class="field">
    <%= form.label 'Required Flowrate' %>
    <%= form.number_field :flowrate, id: :pump_flowrate %>
  </div>

  <div class="field">
    <%= form.label 'Total Developed Head (TDH)' %>
    <%= form.number_field :dev_head, id: :pump_dev_head %>
  </div>

  <div class="field">
    <%= form.label 'Required Assembly' %>
    <%= form.text_field :assembly, id: :pump_assembly %>
  </div>

  <div>
    <%= form.label 'Quantity' %>
    <%= form.number_field :quantity, id: :pump_quantity %>
  </div>

  <div class="field">
    <%= form.label 'Restrictions' %>
    <%= form.text_area :restrictions, id: :pump_restrictions %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pumps/_index.html.erb
<div class="tableHeader">
  <div class="dataColumn">Item Number</div>
  <div class="dataColumn">Pump Type</div>
  <div class="dataColumn">Stages</div>
  <div class="dataColumn">Flow Rate</div>
  <div class="dataColumn">Total Developed Head (TDH)</div>
  <div class="dataColumn">Provided Assemblies</div>
  <div class="dataColumn">Quantity</div>
  <div class="dataColumn">Restrictions</div>
</div>

<% job.pumps.each do |pump| %>
  <div class="<%= pump.item_num.odd? ? 'odd-part' : 'even-part' %> row">
    <div class="data"><%= pump.item_num %></div>
    <div class="data"><%= pump.product_type %></div>
    <div class="data"><%= pump.stages %></div>
    <div class="data"><%= pump.flowrate %></div>
    <div class="data"><%= pump.dev_head %></div>
    <div class="data"><%= pump.assembly %></div>
    <div class="data"><%= pump.quantity %></div>
    <div class="data"><%= pump.restrictions %></div>
  </div>
<% end %>

app/views/pumps/edit.html.erb
<h1>Editing Pump</h1>

<%= render 'form', pump: @pump %>

<%= link_to 'Show', @pump %> |
<%= link_to 'Back', pumps_path %>

app/views/pumps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pumps</h1>

<table>
  <thead>
    <tr>
      <th>Product type</th>
      <th>Stages</th>
      <th>Flowrate</th>
      <th>Dev head</th>
      <th>Assembly</th>
      <th>Restrictions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pumps.each do |pump| %>
      <tr>
        <td><%= pump.product_type %></td>
        <td><%= pump.stages %></td>
        <td><%= pump.flowrate %></td>
        <td><%= pump.dev_head %></td>
        <td><%= pump.assembly %></td>
        <td><%= pump.restrictions %></td>
        <td><%= link_to 'Show', pump %></td>
        <td><%= link_to 'Edit', edit_pump_path(pump) %></td>
        <td><%= link_to 'Destroy', pump, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pump', new_pump_path %>

app/views/pumps/new.html.erb
<h1>New Pump</h1>

<%= render 'form', pump: @pump %>

<%= link_to 'Back', pumps_path %>

app/views/pumps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product type:</strong>
  <%= @pump.product_type %>
</p>

<p>
  <strong>Stages:</strong>
  <%= @pump.stages %>
</p>

<p>
  <strong>Flowrate:</strong>
  <%= @pump.flowrate %>
</p>

<p>
  <strong>Dev head:</strong>
  <%= @pump.dev_head %>
</p>

<p>
  <strong>Assembly:</strong>
  <%= @pump.assembly %>
</p>

<p>
  <strong>Restrictions:</strong>
  <%= @pump.restrictions %>
</p>

<%= link_to 'Edit', edit_pump_path(@pump) %> |
<%= link_to 'Back', pumps_path %>